#
# Configuration for staging environment
#
version: 1.0
app:
  endpoints: public

  # build id to deploy. if 'version' is commented out, the application is not deployed
  version: "b2e2a116-7652-4d79-8d10-ceba9563e306"

  # number of instances
  instances:
    # min number of instances. can be 0 for scale to 0. default to 1.
    min: 1
    
    # max number of instances. defaults to 1 if min == 0, otherwise defaults to min
    max: 1
    
  resources:
    # max cpu. memory limit is based on cpu value: 1:3 memory ratio, e.g. 1 cpu == 3 gb
    cpu: 1
