#
# Configuration for staging environment
#
version: 1.0
app:
  endpoints: public

  # build id to deploy. if 'version' is commented out, the application is not deployed
  version: "f5b77bbb-0abe-429c-9d52-6a1902129cb3"

  # number of instances
  instances:
    # min number of instances. can be 0 for scale to 0. default to 1.
    min: 3
    
    # max number of instances. defaults to 1 if min == 0, otherwise defaults to min
    max: 6
    
  resources:
    # max cpu. memory limit is based on cpu value: 1:3 memory ratio, e.g. 1 cpu == 3 gb
    cpu: 1
